/* eslint-disable */

export const FILE_NULL			= require('@/assets/favicons/file/null.svg')
export const FILE_JS				= require('@/assets/favicons/file/js.svg')
export const FILE_WASM			= require('@/assets/favicons/file/wasm.svg')
export const FILE_TS				= require('@/assets/favicons/file/ts.svg')
export const FILE_CPP				= require('@/assets/favicons/file/cpp.svg')
export const FILE_C					= require('@/assets/favicons/file/c.svg')
export const FILE_HTML			= require('@/assets/favicons/file/html.svg')
export const FILE_DEV				= require('@/assets/favicons/file/develop.svg')
export const FILE_USER			= require('@/assets/favicons/file/user.svg')
export const FILE_CODEGLO   = require('@/assets/favicons/file/codeglo.svg')

export const FOLDER_NULL		= require('@/assets/favicons/folder/null.svg')
export const FOLDER_JS			= require('@/assets/favicons/folder/js.svg')
export const FOLDER_WASM		= require('@/assets/favicons/folder/wasm.svg')
export const FOLDER_TS			= require('@/assets/favicons/folder/ts.svg')
export const FOLDER_CPP			= require('@/assets/favicons/folder/cpp.svg')
export const FOLDER_C				= require('@/assets/favicons/folder/c.svg')
export const FOLDER_HTML		= require('@/assets/favicons/folder/html.svg')
export const FOLDER_DEV			= require('@/assets/favicons/folder/develop.svg')
export const FOLDER_USER		= require('@/assets/favicons/folder/user.svg')
export const FOLDER_CODEGLO = require('@/assets/favicons/folder/codeglo.svg')

export const PROJECT_NULL		= require('@/assets/favicons/project/null.svg')
export const PROJECT_JS			= require('@/assets/favicons/project/js.svg')
export const PROJECT_WASM		= require('@/assets/favicons/project/wasm.svg')
export const PROJECT_TS			= require('@/assets/favicons/project/ts.svg')
export const PROJECT_CPP		= require('@/assets/favicons/project/cpp.svg')
export const PROJECT_C			= require('@/assets/favicons/project/c.svg')
export const PROJECT_HTML		= require('@/assets/favicons/project/html.svg')
export const PROJECT_DEV		= require('@/assets/favicons/project/develop.svg')
export const PROJECT_USER		= require('@/assets/favicons/project/user.svg')
export const PROJECT_CODEGLO= require('@/assets/favicons/project/codeglo.svg')

export const CMD = require('@/assets/favicons/cmd.svg')
export const FAVICON = require('@/assets/favicons/favicon.svg')
export const TYPOGRAPHY = require('@/assets/favicons/typography.svg')