# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  serve:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install && echo "Install successfully"
    - run: npm run lint && echo "Lint successfully"
    - run: npm run build && echo "Build successfully"
    # - run: npm run serve
    # - run: echo "the project directory is - $CI_PROJECT_DIR"
    # - run: echo $CI_PROJECT_DIR ; echo
    # - run: echo "and where am I? - $PWD"
